# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Site settings
# 6. Site favicons & manifest icons
# 7. Site navigation

# Adding theme
remote_theme: daviddarnes/alembic

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
jekyll-mentions: https://facebook.com # jekyll-mentions > service used when @replying
twitter:
  username: SayarGhoshRoy # jekyll-seo-tag > Owners twitter username
author: SayarGhoshRoy # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Sayar Ghosh Roy # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/Sayar.Ghosh.Roy
    - https://www.linkedin.com/in/sayarghoshroy
    - https://github.com/sayarghoshroy
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: India/Kolkata # Timezone for blog posts and alike

# 5. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Sayar's Work" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo@120px.png" # Site logo, also used in jekyll-seo-tag
description: "Hi! I am Sayar Ghosh Roy. You can access some of my projects and a few created resources here." # Site description and default description, also used in jekyll-seo-tag
url: "https://sayarghoshroy.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/sayarghoshroy/sayarghoshroy.github.io"
email: "sayar.1997@gmail.com"

# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 6. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 7. Site navigation
navigation_header:
- title: Home
  url: /
- title: My Work
  url: /work/

navigation_footer:
- title: I Love Pandas
  url: https://www.worldwildlife.org/species/giant-panda

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/sayarghoshroy
  GitHub: https://github.com/sayarghoshroy
  facebook: https://www.facebook.com/Sayar.Ghosh.Roy
  email: mailto:sayar.1997@gmail.com
